export ROOTDIR=$(pwd)
export SYSCALL_PATH=$ROOTDIR/syscall
export STRING_PATH=$ROOTDIR/string
export STDLIB_PATH=$ROOTDIR/stdlib

export C_INCLUDE_PATH=$ROOTDIR/include
export LD_LIBRARY_PATH=$SYS_CALL_PATH:$STRING_PATH:$STD_LIB_PATH:$LD_LIBRARY_PATH
